version: '3.1'

services:
  # user-service:
  #   build: ./user-service
  #   ports:
  #     - 50053:50051
  #   environment:
  #     MICRO_ADDRESS: ":50051"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  # database:
  #   image: postgres
  #   ports:
  #     - 5432:5432

  shippy-service-vessel:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  shippy-service-consignment:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  shippy-service-consignment-cli:
    build: ./consignment-cli
